project:
  type: website
  
execute:
  freeze: auto

website:
  title: "Aide-mémoire SAS - R"

  page-footer:
    right: "Ce site a été créé avec [Quarto](https://quarto.org/)"
    
  sidebar:
    pinned: true
    align: center
    style: "docked"
    contents:
      - href: 01-aide_memoire_r_sas.qmd
        text: "Aide-mémoire"
      - href: 03-mise_en_garde.qmd
        text: "Mise en garde"
      - href: Trucs et astuces en R.qmd
        text: "Trucs et astuces"
      - href: 04-specificites_sas_r.qmd
        text: "Spécificités de SAS et R"
      - href: 02-avantages_inconvenients_env_R.qmd
        text: "Avantages et inconvénients des environnements R"
        
format:
  html:
#    theme:
#      light: flatly
#      dark: darkly
    code-copy: true
    code-overflow: wrap
    toc: true
