project:
  type: website
  
execute:
  freeze: auto

website:
  title: "Aide-mémoire SAS - R"

  page-footer:
    right: "Ce site a été créé avec [Quarto](https://quarto.org/)"
    
  sidebar:
    pinned: true
    align: center
    style: "docked"
    contents:
      - href: 01-integration_chap_aide_mémoire_SAS-R.qmd
        text: "Aide-mémoire"
      - href: 02-trucs_et_astuces_en_R.qmd
        text: "Trucs et astuces"
      - href: 03-avantages_inconvenients_env_R.qmd
        text: "Avantages et inconvénients des environnements R"
        
format:
  html:
    theme:
      light: flatly
      dark: darkly
    code-copy: true
    code-overflow: wrap
    toc: true
